import {test,expect} from '@playwright/test';
test('additional-only selection, grades, miracle, equipment filtering and persistence',async({page})=>{
  await page.goto('/?item=dreamy');
  await expect(page.locator('#additionalStat')).toHaveValue('');
  await page.locator('[data-target="0"]').click();
  await page.locator('#additionalStat').selectOption('주스탯');
  await expect(page.locator('.goal-tags')).toContainText('에디셔널 주스탯');
  await page.locator('#calculation-details>summary').click();
  await page.locator('#miracle').uncheck();
  const before=await page.locator('#additional-upgrade-cost').textContent();
  await page.locator('#miracle').check();
  await expect(page.locator('#additional-upgrade-cost')).not.toHaveText(before);
  await page.locator('#additionalGrade').selectOption('legendary');
  await expect(page.locator('#additional-upgrade-cost')).toHaveText('0 메소');
  await page.goto('/');
  await expect(page.locator('#additionalStat')).toHaveValue('주스탯');
  await expect(page.locator('#additionalGrade')).toHaveValue('legendary');
  await expect(page.locator('#miracle')).toBeChecked();
  await page.locator('.simulation-card>summary').click();
  await page.locator('#simulate-start').click();
  await expect(page.locator('#simulation-output')).toContainText('에디셔널 옵션 재설정');
  await page.locator('[data-item="eternal-main"]').click();
  await page.locator('[data-part="6"]').click();
  await page.locator('#additionalStat').selectOption('쿨타임 감소');
  await expect(page.locator('#additionalThreshold option')).toHaveText(['1초 이상','2초 이상','3초 이상']);
  await page.locator('[data-part="14"]').click();
  await expect(page.locator('#additionalStat')).toHaveValue('');
  await expect(page.locator('#additionalStat option[value="공격력"]')).toHaveCount(0);
  await expect(page.locator('#form-error')).toBeHidden();
});
