import {test,expect} from '@playwright/test';
test('gold cube equipment buttons, boss cube counts and grade restrictions',async({page})=>{
  await page.goto('/');
  await page.getByRole('link',{name:'큐브 기대값',exact:true}).click();
  await expect(page).toHaveURL(/gold-cube.html$/);
  await expect(page.locator('#cube-price')).toHaveCount(0);
  await expect(page.locator('#gold-equipment button')).toHaveCount(20);
  await expect(page.locator('#gold-custom-goal')).toBeHidden();
  const main=page.locator('#stat-preset-results .mitra-preset');
  await expect(main).toHaveCount(4);
  const initial=await main.first().innerText();
  await page.locator('#start-grade').selectOption('legendary');
  await expect(main.first()).not.toHaveText(initial);
  await page.locator('[data-item=dreamy]').click();
  await expect(main).toHaveCount(4);
  await page.locator('[data-item=arcane]').click();
  await expect(main).toHaveCount(10);
  await page.locator('[data-part="11"]').click();
  await expect(main).toHaveCount(7);
  await page.locator('[data-item=astra]').click();
  await expect(page.locator('#gold-custom-goal')).toBeVisible();
  await page.locator('[data-item=mitra]').click();
  const icon=page.locator('[data-item=mitra] img');
  await expect(icon).toBeVisible();
  await expect.poll(()=>icon.evaluate(img=>img.naturalWidth)).toBeGreaterThan(0);
  await expect(page.locator('#gold-custom-goal')).toBeHidden();
  await expect(page.locator('#mitra-preset-results .mitra-preset')).toHaveCount(3);
  const before=await page.locator('#mitra-preset-results').innerText();
  await page.locator('#start-grade').selectOption('epic');
  await expect(page.locator('#mitra-preset-results')).not.toHaveText(before);
  await page.locator('[data-item=astra]').click();
  await expect(page.locator('#gold-custom-goal')).toBeVisible();
  await page.locator('[data-item=michaela]').click();
  await expect(page.locator('#stat-preset-results .mitra-preset')).toHaveCount(4);
  await expect(page.locator('#stat-preset-results')).toContainText('메소 획득량 40% 이상');
  await expect(page.locator('#stat-preset-results')).toContainText('드롭률 20% + 메소 획득량 20%');
  await expect.poll(()=>page.locator('[data-item=michaela] img').evaluate(img=>img.naturalWidth)).toBeGreaterThan(0);
  await expect(page.locator('#gold-custom-goal')).toBeHidden();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('link',{name:'장비 기대값',exact:true}).click();
  await expect(page).toHaveURL(/\/$/);
});
test('gold options recover after a failed probability download',async({page})=>{
  let fail=true;
  await page.route('**/data/gold-potential.json*',async route=>{
    if(fail)await route.fulfill({status:503,body:'Unavailable'});
    else await route.continue();
  });
  await page.goto('/gold-cube.html');
  await page.locator('[data-item=mitra]').click();
  await expect(page.locator('#gold-retry')).toBeVisible();
  await expect(page.locator('#gold-stat')).toBeDisabled();
  fail=false;
  await page.locator('#gold-retry').click();
  await expect(page.locator('#mitra-preset-results .mitra-preset')).toHaveCount(3);
});
test('silver switch uses unique goals and hides legendary loot presets',async({page})=>{
  await page.goto('/gold-cube.html');
  await page.locator('#stat-preset-results').waitFor();
  await page.locator('#start-grade').selectOption('legendary');
  await page.locator('[data-cube=silver]').click();
  await expect(page.locator('#target-grade')).toHaveValue('unique');
  await expect(page.locator('#start-grade option[value=legendary]')).toHaveJSProperty('disabled',true);
  await expect(page.locator('#silver-preset-results .mitra-preset')).toHaveCount(5);
  await page.locator('#gold-miracle').uncheck();
  await expect(page.locator('#silver-upgrade-count')).toHaveText('84.33개');
  await page.locator('[data-item=michaela]').click();
  await expect(page.locator('#gold-result')).toContainText('골드 큐브로 전환');
  await expect(page.locator('#stat-preset-results')).toHaveCount(0);
  await page.locator('[data-cube=gold]').click();
  await expect(page.locator('#start-grade')).toHaveValue('legendary');
  await expect(page.locator('#stat-preset-results .mitra-preset')).toHaveCount(4);
  await page.locator('[data-cube=silver]').click();
  await page.locator('[data-item=mitra]').click();
  await expect(page.locator('#silver-preset-results .mitra-preset')).toHaveCount(10);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
