import {test,expect} from '@playwright/test';
test('gold cube equipment buttons, boss cube counts and grade restrictions',async({page})=>{
  await page.goto('/');
  await page.getByRole('link',{name:'골드 큐브',exact:true}).click();
  await expect(page).toHaveURL(/gold-cube.html$/);
  await expect(page.locator('#cube-price')).toHaveCount(0);
  await expect(page.locator('#gold-equipment button')).toHaveCount(18);
  const cost=await page.locator('#mesos-cost').innerText();
  const count=await page.locator('#gold-count').innerText();
  await expect(page.locator('#gold-total')).toContainText('확인 필요');
  await page.getByRole('button',{name:'고통의 근원',exact:true}).click();
  await expect(page.getByRole('button',{name:'고통의 근원',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#mesos-cost')).not.toHaveText(cost);
  await expect(page.locator('#gold-count')).toHaveText(count);
  await page.locator('#start-grade').selectOption('rare');
  await page.locator('#target-grade').selectOption('epic');
  await page.locator('#gold-miracle').uncheck();
  await expect(page.locator('#gold-count')).toHaveText('12.5개');
  await page.locator('#start-grade').selectOption('unique');
  await page.locator('#gold-stat').selectOption('주스탯');
  await expect(page.locator('#target-grade')).toHaveValue('legendary');
  await expect(page.locator('#gold-breakdown tbody tr')).toHaveCount(1);
  await page.getByRole('button',{name:'몽환의 벨트',exact:true}).click();
  await expect(page.locator('#gold-option-count')).toBeVisible();
  await page.locator('#start-grade').selectOption('legendary');
  await expect(page.locator('#gold-breakdown')).toContainText('등업 비용이 없습니다');
  await page.getByRole('button',{name:'아케인셰이드 방어구',exact:true}).click();
  await page.locator('#gold-stat').selectOption('쿨타임 감소');
  await page.getByRole('button',{name:'장갑',exact:true}).click();
  await expect(page.locator('#gold-stat')).toHaveValue('');
  await page.locator('#gold-stat').selectOption('크리티컬 데미지');
  await expect(page.locator('#gold-option-count')).toBeVisible();
  await page.getByText('실제 사용 비용 입력',{exact:true}).click();
  await page.locator('#gold-fee').fill('100000');
  await expect(page.locator('#gold-total')).toContainText('억 메소');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('link',{name:'장비 기대값',exact:true}).click();
  await expect(page).toHaveURL(/\/$/);
});
