import {test,expect} from '@playwright/test';
test('starting stars change remaining cost, persist, and work with no target',async({page})=>{
  await page.goto('/?item=dreamy');
  await expect(page.locator('#start')).toHaveValue('0');
  const original=await page.locator('.total').textContent();
  await page.locator('#start').selectOption('17');
  await expect(page.locator('.total-label')).toContainText('17★ → 22★');
  await expect(page.locator('.total')).not.toHaveText(original);
  await expect(page.locator('#stage-rows tr')).toHaveCount(5);
  await page.goto('/');
  await expect(page.locator('#start')).toHaveValue('17');
  await page.locator('#start').selectOption('26');
  await expect(page.locator('#target')).toHaveValue('26');
  await expect(page.locator('[data-target="25"]')).toBeDisabled();
  await expect(page.locator('.breakdown>div').filter({hasText:'스타포스 강화'}).locator('dd')).toHaveText('0 메소');
  await page.locator('[data-target="27"]').click();
  await expect(page.locator('.total-label')).toContainText('26★ → 27★');
  await page.locator('[data-target="0"]').click();
  await expect(page.locator('#form-error')).toBeHidden();
  await page.reload();
  await expect(page.locator('#start')).toHaveValue('26');
  await expect(page.locator('#target')).toHaveValue('0');
  await page.locator('#start').selectOption('17');
  await page.locator('[data-target="17"]').click();
  await page.locator('.simulation-card>summary').click();
  await page.locator('#simulate-start').click();
  await expect(page.locator('#simulation-status')).toContainText('목표 달성');
  await expect(page.locator('#simulation-output')).toContainText('17성');
});
