"""Extract crystal price revisions from official live-server patch notes."""
import json
import re
from pathlib import Path
import requests
from bs4 import BeautifulSoup

changes = []
for article, effective in [(806, '2026-06-18'), (813, '2026-09-17')]:
    url = f'https://maplestory.nexon.com/news/update/{article}'
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    soup = BeautifulSoup(response.content, 'html.parser')
    found = 0
    for table in soup.select('table'):
        if '변경 가격' not in table.get_text(' ', strip=True):
            continue
        for row in table.select('tr'):
            cells = [cell.get_text(' ', strip=True) for cell in row.select('td,th')]
            if len(cells) != 3 or not re.fullmatch(r'[\d, ]+', cells[-1]):
                continue
            match = re.fullmatch(r'(.+?)\s*\((.+?)\)', cells[0])
            if not match:
                raise ValueError(cells)
            name, difficulty = match.groups()
            date = effective
            if name == '검은 마법사':
                date = '2026-07-01' if article == 806 else '2026-10-01'
            changes.append(dict(name=name, difficulty=difficulty, effective=date,
                                before=int(cells[1].replace(',', '').replace(' ', '')),
                                price=int(cells[2].replace(',', '').replace(' ', '')), source=url))
            found += 1
    if found < 40:
        raise ValueError(f'Incomplete price table: {url}')
target = Path(__file__).resolve().parents[1] / 'public/js/boss-prices.js'
target.write_text('// Official crystal price revisions; generated by scripts/update-boss-prices.py\n'
                  + 'export const PRICE_CHANGES = ' + json.dumps(changes, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Updated {len(changes)} official price revisions')
